/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.NhanVienDAO;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.BoPhan;
import model.ChucVu;
import model.NhanVien;

/**
 *
 * @author NamTang
 */
public class hosoView extends javax.swing.JFrame {
    homeView hv = new homeView();
    /**
     * Creates new form hosoView
     */
    public hosoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainluongPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        clearhoso_btn = new javax.swing.JButton();
        trovehoso_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchmanv_tf = new javax.swing.JTextField();
        hosoprint_jpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        getngaysinh_lb = new javax.swing.JLabel();
        gethesoluong_lb = new javax.swing.JLabel();
        getgioitinh_lb = new javax.swing.JLabel();
        gethoten_lb = new javax.swing.JLabel();
        getsodienthoai_lb = new javax.swing.JLabel();
        getdiachi_lb = new javax.swing.JLabel();
        getngayvaolam = new javax.swing.JLabel();
        getbophan_lb = new javax.swing.JLabel();
        getchucvu_lb = new javax.swing.JLabel();
        getluong_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainluongPanel.setBackground(new java.awt.Color(204, 255, 255));
        mainluongPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mainluongPanel.setMinimumSize(new java.awt.Dimension(900, 600));
        mainluongPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("XEM HỒ SƠ");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 0, 0)));
        mainluongPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 54));

        clearhoso_btn.setBackground(new java.awt.Color(255, 51, 51));
        clearhoso_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearhoso_btn.setForeground(new java.awt.Color(255, 255, 255));
        clearhoso_btn.setText("Clear");
        clearhoso_btn.setBorderPainted(false);
        clearhoso_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearhoso_btn.setFocusPainted(false);
        clearhoso_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearhoso_btnActionPerformed(evt);
            }
        });
        mainluongPanel.add(clearhoso_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 110, 30));

        trovehoso_btn.setBackground(new java.awt.Color(0, 0, 255));
        trovehoso_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        trovehoso_btn.setForeground(new java.awt.Color(255, 255, 255));
        trovehoso_btn.setText("Back");
        trovehoso_btn.setBorderPainted(false);
        trovehoso_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trovehoso_btn.setFocusPainted(false);
        trovehoso_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trovehoso_btnActionPerformed(evt);
            }
        });
        mainluongPanel.add(trovehoso_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 110, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Search:");
        mainluongPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 70, 30));

        searchmanv_tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchmanv_tf.setForeground(new java.awt.Color(153, 153, 153));
        searchmanv_tf.setText("Ma nhan vien");
        searchmanv_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchmanv_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchmanv_tfFocusLost(evt);
            }
        });
        searchmanv_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchmanv_tfKeyPressed(evt);
            }
        });
        mainluongPanel.add(searchmanv_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 180, 30));

        hosoprint_jpanel.setBackground(new java.awt.Color(204, 204, 204));
        hosoprint_jpanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        hosoprint_jpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Họ tên:");
        hosoprint_jpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Giới tính:");
        hosoprint_jpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ngày sinh:");
        hosoprint_jpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Số điện thoại:");
        hosoprint_jpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Ngày vào làm:");
        hosoprint_jpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Địa chỉ:");
        hosoprint_jpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 50, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Bộ phận làm việc:");
        hosoprint_jpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Chức vụ:");
        hosoprint_jpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Lương cơ bản($):");
        hosoprint_jpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 120, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setText("HỒ SƠ");
        hosoprint_jpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Hệ số lương:");
        hosoprint_jpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 90, 20));

        getngaysinh_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getngaysinh_lb.setText("01/01/2003");
        hosoprint_jpanel.add(getngaysinh_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 100, 20));

        gethesoluong_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gethesoluong_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gethesoluong_lb.setText("1");
        hosoprint_jpanel.add(gethesoluong_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 70, 20));

        getgioitinh_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getgioitinh_lb.setText("Nam");
        hosoprint_jpanel.add(getgioitinh_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 100, 20));

        gethoten_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gethoten_lb.setText("Nguyen Van A");
        hosoprint_jpanel.add(gethoten_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 220, 20));

        getsodienthoai_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getsodienthoai_lb.setText("0123456789");
        hosoprint_jpanel.add(getsodienthoai_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 210, 20));

        getdiachi_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getdiachi_lb.setText("Can Tho");
        hosoprint_jpanel.add(getdiachi_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 210, 30));

        getngayvaolam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getngayvaolam.setText("01/12/2023");
        hosoprint_jpanel.add(getngayvaolam, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 210, 20));

        getbophan_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getbophan_lb.setText("Bo phan kinh doanh");
        hosoprint_jpanel.add(getbophan_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 210, 20));

        getchucvu_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getchucvu_lb.setText("Nhan vien");
        hosoprint_jpanel.add(getchucvu_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 210, 20));

        getluong_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getluong_lb.setText("0");
        hosoprint_jpanel.add(getluong_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 100, 20));

        mainluongPanel.add(hosoprint_jpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 560, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainluongPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainluongPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void trovehoso_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trovehoso_btnActionPerformed
        hv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_trovehoso_btnActionPerformed

    private void clearhoso_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearhoso_btnActionPerformed
        gethoten_lb.setText("");
        getgioitinh_lb.setText("");
        getsodienthoai_lb.setText("");
        getngaysinh_lb.setText("");
        getngayvaolam.setText("");
        getdiachi_lb.setText("");
        getbophan_lb.setText("");
        getchucvu_lb.setText("");
        getluong_lb.setText("");
        gethesoluong_lb.setText("");
        searchmanv_tf.setText("Ma nhan vien");
        searchmanv_tf.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_clearhoso_btnActionPerformed

    private void searchmanv_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchmanv_tfFocusGained
        if(searchmanv_tf.getText().equals("Ma nhan vien")){
            searchmanv_tf.setText("");
            searchmanv_tf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_searchmanv_tfFocusGained

    private void searchmanv_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchmanv_tfFocusLost
        if(searchmanv_tf.getText().equals("")){
            searchmanv_tf.setText("Ma nhan vien");
            searchmanv_tf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_searchmanv_tfFocusLost

    private void searchmanv_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchmanv_tfKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String manv = searchmanv_tf.getText();            
            NhanVienDAO nhanviendao = new NhanVienDAO();
            NhanVien nhanvien = new NhanVien();
            nhanvien = nhanviendao.selectBymaNV(manv);
            if(nhanvien==null){
                JOptionPane.showMessageDialog(null, "Mã nhân viên không tồn tại!");
                return;
            }
            gethoten_lb.setText(nhanvien.getHoTen());
            getngaysinh_lb.setText(String.valueOf(nhanvien.getNgaySinh()));
            getgioitinh_lb.setText(nhanvien.getGioiTinh());
            getsodienthoai_lb.setText(nhanvien.getSdt());
            getdiachi_lb.setText(nhanvien.getDiaChi());
            getngayvaolam.setText(String.valueOf(nhanvien.getNgayVaoLam()));   
            getbophan_lb.setText(nhanvien.getBoPhan().getTenBP());
            getchucvu_lb.setText(nhanvien.getChucVu().getTenCV());
            getluong_lb.setText(String.valueOf(nhanvien.getLuongCB()));
            gethesoluong_lb.setText(String.valueOf(nhanvien.getHeSoLuong()));
        }
    }//GEN-LAST:event_searchmanv_tfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hosoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hosoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hosoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hosoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hosoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearhoso_btn;
    private javax.swing.JLabel getbophan_lb;
    private javax.swing.JLabel getchucvu_lb;
    private javax.swing.JLabel getdiachi_lb;
    private javax.swing.JLabel getgioitinh_lb;
    private javax.swing.JLabel gethesoluong_lb;
    private javax.swing.JLabel gethoten_lb;
    private javax.swing.JLabel getluong_lb;
    private javax.swing.JLabel getngaysinh_lb;
    private javax.swing.JLabel getngayvaolam;
    private javax.swing.JLabel getsodienthoai_lb;
    private javax.swing.JPanel hosoprint_jpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainluongPanel;
    private javax.swing.JTextField searchmanv_tf;
    private javax.swing.JButton trovehoso_btn;
    // End of variables declaration//GEN-END:variables
}
