/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JPanel;

/**
 *
 * @author NamTang
 */
public class inBienNhanView extends javax.swing.JFrame {

    /**
     * Creates new form inBienNhanView
     */
    public inBienNhanView() {
        initComponents();
        mabiennhan_lb.setText(luongView.temp_maBN);
        manhanvien_lb.setText(luongView.temp_maNV);
        hotennhanvien_lb.setText(luongView.temp_hoTen);
        ngaynhan_lb.setText(luongView.temp_ngayNhan);
        thuongthem_lb.setText(luongView.temp_thuongThem);
        tong_lb.setText(luongView.temp_tong);
        nguoinhap_lb.setText(luongView.temp_nguoiNhap);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainluongPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        printbn_btn = new javax.swing.JButton();
        biennhan_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nguoinhap_lb = new javax.swing.JLabel();
        hotennhanvien_lb = new javax.swing.JLabel();
        mabiennhan_lb = new javax.swing.JLabel();
        manhanvien_lb = new javax.swing.JLabel();
        ngaynhan_lb = new javax.swing.JLabel();
        thuongthem_lb = new javax.swing.JLabel();
        tong_lb = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(901, 600));
        setSize(new java.awt.Dimension(901, 601));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainluongPanel.setBackground(new java.awt.Color(204, 255, 255));
        mainluongPanel.setMinimumSize(new java.awt.Dimension(900, 600));
        mainluongPanel.setPreferredSize(new java.awt.Dimension(900, 600));
        mainluongPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("IN BIÊN NHẬN TIỀN");
        mainluongPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 360, 60));

        printbn_btn.setBackground(new java.awt.Color(255, 0, 0));
        printbn_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        printbn_btn.setForeground(new java.awt.Color(255, 255, 255));
        printbn_btn.setText("Print");
        printbn_btn.setBorderPainted(false);
        printbn_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printbn_btn.setFocusPainted(false);
        printbn_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbn_btnActionPerformed(evt);
            }
        });
        mainluongPanel.add(printbn_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 100, 30));

        biennhan_panel.setBackground(new java.awt.Color(204, 204, 204));
        biennhan_panel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        biennhan_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BIÊN NHẬN");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        biennhan_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Người nhập:");
        biennhan_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 100, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mã biên nhận:");
        biennhan_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 100, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mã nhân viên:");
        biennhan_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 100, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Họ tên nhân viên:");
        biennhan_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 130, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Ngày nhận:");
        biennhan_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 100, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Thưởng thêm:");
        biennhan_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 100, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Tổng:");
        biennhan_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 100, 20));

        nguoinhap_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        biennhan_panel.add(nguoinhap_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 180, 20));

        hotennhanvien_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        biennhan_panel.add(hotennhanvien_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 180, 20));

        mabiennhan_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        biennhan_panel.add(mabiennhan_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 180, 20));

        manhanvien_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        biennhan_panel.add(manhanvien_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 180, 20));

        ngaynhan_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        biennhan_panel.add(ngaynhan_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 180, 20));

        thuongthem_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        biennhan_panel.add(thuongthem_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 180, 20));

        tong_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        biennhan_panel.add(tong_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 180, 20));

        mainluongPanel.add(biennhan_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 470, 400));

        back_btn.setBackground(new java.awt.Color(0, 0, 255));
        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("Back");
        back_btn.setBorderPainted(false);
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.setFocusPainted(false);
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        mainluongPanel.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 100, 30));

        getContentPane().add(mainluongPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printbn_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbn_btnActionPerformed
        printRecord(biennhan_panel);
    }//GEN-LAST:event_printbn_btnActionPerformed
    
       
    private void printRecord(JPanel panel){
        PrinterJob printerJob = PrinterJob.getPrinterJob(); 
        printerJob.setJobName("Print Bien Lai");
        printerJob.setPrintable(new Printable(){
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if(pageIndex > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D graphics2D = (Graphics2D)graphics;
                panel.paint(graphics2D);
                return Printable.PAGE_EXISTS;
            }
            
        });
        boolean returning = printerJob.printDialog();
        if(returning){
            try {
                printerJob.print();
            } catch (Exception e) {
            }
        }
    }
    
    
    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        luongView luongview = new luongView();
        luongview.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inBienNhanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inBienNhanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inBienNhanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inBienNhanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inBienNhanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JPanel biennhan_panel;
    private javax.swing.JLabel hotennhanvien_lb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mabiennhan_lb;
    private javax.swing.JPanel mainluongPanel;
    private javax.swing.JLabel manhanvien_lb;
    private javax.swing.JLabel ngaynhan_lb;
    private javax.swing.JLabel nguoinhap_lb;
    private javax.swing.JButton printbn_btn;
    private javax.swing.JLabel thuongthem_lb;
    private javax.swing.JLabel tong_lb;
    // End of variables declaration//GEN-END:variables
}
