/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BienNhanDAO;
import controller.ChucVuDAO;
import controller.NhanVienDAO;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.SimpleFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;
import model.BienNhan;
import model.BoPhan;
import model.ChucVu;
import model.NhanVien;

/**
 *
 * @author NamTang
 */
public class luongView extends javax.swing.JFrame {
     homeView hv = new homeView();
    /**
     * Creates new form luongView
     */
    public luongView() {
        initComponents();
        JTableHeader header = luongtable.getTableHeader();
        header.setFont( new Font("Segoe UI",Font.BOLD,12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainluongPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        troveluong_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        luongtable = new javax.swing.JTable();
        timkiem_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        manvluong_tf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        updateluong_btn = new javax.swing.JButton();
        clearluong_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        luongnvluong_tf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        hesoluongnvluong_tf = new javax.swing.JTextField();
        hotennvluong_tf = new javax.swing.JLabel();
        PanelTinhLuong = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        calculateluong_btn = new javax.swing.JButton();
        saveluong_btn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tongtien_lb = new javax.swing.JLabel();
        manvcalluong_tf = new javax.swing.JTextField();
        thuongthem_tf = new javax.swing.JTextField();
        ngaynhan_jcal = new com.toedter.calendar.JDateChooser();
        cleartinhluong_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hotennv_lb = new javax.swing.JLabel();
        nguoinhap_tf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        hesoluong_lb = new javax.swing.JLabel();
        luongcb_lb = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        printluong_btn = new javax.swing.JButton();
        resettbluong_btn = new javax.swing.JButton();
        cleartbluong_btn = new javax.swing.JButton();
        printtbluong_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainluongPanel.setBackground(new java.awt.Color(204, 255, 255));
        mainluongPanel.setMinimumSize(new java.awt.Dimension(900, 600));
        mainluongPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ LƯƠNG NHÂN VIÊN");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 255, 51)));

        troveluong_btn.setBackground(new java.awt.Color(102, 102, 102));
        troveluong_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        troveluong_btn.setForeground(new java.awt.Color(255, 255, 255));
        troveluong_btn.setText("Back");
        troveluong_btn.setBorderPainted(false);
        troveluong_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        troveluong_btn.setFocusPainted(false);
        troveluong_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                troveluong_btnActionPerformed(evt);
            }
        });

        luongtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã nhân viên", "Họ tên", "Giới tính", "Chức vụ", "Bộ phận", "Lương cơ bản", "Hệ số lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(luongtable);
        if (luongtable.getColumnModel().getColumnCount() > 0) {
            luongtable.getColumnModel().getColumn(0).setResizable(false);
            luongtable.getColumnModel().getColumn(0).setPreferredWidth(25);
            luongtable.getColumnModel().getColumn(1).setResizable(false);
            luongtable.getColumnModel().getColumn(2).setResizable(false);
            luongtable.getColumnModel().getColumn(3).setResizable(false);
            luongtable.getColumnModel().getColumn(4).setResizable(false);
            luongtable.getColumnModel().getColumn(5).setResizable(false);
            luongtable.getColumnModel().getColumn(6).setResizable(false);
            luongtable.getColumnModel().getColumn(7).setResizable(false);
        }

        timkiem_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                timkiem_tfKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Search:");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manvluong_tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manvluong_tf.setForeground(new java.awt.Color(153, 153, 153));
        manvluong_tf.setText("'A0000' Enter");
        manvluong_tf.setPreferredSize(new java.awt.Dimension(60, 30));
        manvluong_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                manvluong_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                manvluong_tfFocusLost(evt);
            }
        });
        manvluong_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                manvluong_tfKeyPressed(evt);
            }
        });
        jPanel1.add(manvluong_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Mã nhân viên:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Họ tên:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 30));

        updateluong_btn.setBackground(new java.awt.Color(0, 0, 255));
        updateluong_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateluong_btn.setForeground(new java.awt.Color(255, 255, 255));
        updateluong_btn.setText("Update");
        updateluong_btn.setBorderPainted(false);
        updateluong_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateluong_btn.setFocusPainted(false);
        updateluong_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateluong_btnActionPerformed(evt);
            }
        });
        jPanel1.add(updateluong_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, 30));

        clearluong_btn.setBackground(new java.awt.Color(255, 51, 51));
        clearluong_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearluong_btn.setForeground(new java.awt.Color(255, 255, 255));
        clearluong_btn.setText("Clear");
        clearluong_btn.setBorderPainted(false);
        clearluong_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearluong_btn.setFocusPainted(false);
        clearluong_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearluong_btnActionPerformed(evt);
            }
        });
        jPanel1.add(clearluong_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 90, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Lương cơ bản:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 30));

        luongnvluong_tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(luongnvluong_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 180, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Hệ số lương:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 30));

        hesoluongnvluong_tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(hesoluongnvluong_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 180, 30));

        hotennvluong_tf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(hotennvluong_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 180, 30));

        PanelTinhLuong.setBackground(new java.awt.Color(204, 204, 204));
        PanelTinhLuong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TÍNH LƯƠNG");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 255)));
        PanelTinhLuong.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 4, -1, 30));

        calculateluong_btn.setBackground(new java.awt.Color(0, 0, 255));
        calculateluong_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        calculateluong_btn.setForeground(new java.awt.Color(255, 255, 255));
        calculateluong_btn.setText(" Calculate");
        calculateluong_btn.setBorderPainted(false);
        calculateluong_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calculateluong_btn.setFocusPainted(false);
        calculateluong_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateluong_btnActionPerformed(evt);
            }
        });
        PanelTinhLuong.add(calculateluong_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 90, 31));

        saveluong_btn.setBackground(new java.awt.Color(0, 255, 0));
        saveluong_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveluong_btn.setForeground(new java.awt.Color(255, 255, 255));
        saveluong_btn.setText("Save");
        saveluong_btn.setBorderPainted(false);
        saveluong_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveluong_btn.setFocusPainted(false);
        saveluong_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveluong_btnActionPerformed(evt);
            }
        });
        PanelTinhLuong.add(saveluong_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 90, 31));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Mã nhân viên:");
        PanelTinhLuong.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 100, 24));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Ngày nhận:");
        PanelTinhLuong.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 24));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Thưởng thêm:");
        PanelTinhLuong.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 24));

        tongtien_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tongtien_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelTinhLuong.add(tongtien_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 140, 30));

        manvcalluong_tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manvcalluong_tf.setForeground(new java.awt.Color(153, 153, 153));
        manvcalluong_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        manvcalluong_tf.setText("'A0000' Enter");
        manvcalluong_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                manvcalluong_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                manvcalluong_tfFocusLost(evt);
            }
        });
        manvcalluong_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                manvcalluong_tfKeyPressed(evt);
            }
        });
        PanelTinhLuong.add(manvcalluong_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 140, 24));

        thuongthem_tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PanelTinhLuong.add(thuongthem_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, 24));

        ngaynhan_jcal.setDateFormatString("dd/MM/yyyy");
        ngaynhan_jcal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PanelTinhLuong.add(ngaynhan_jcal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 140, 24));

        cleartinhluong_btn.setBackground(new java.awt.Color(255, 51, 51));
        cleartinhluong_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cleartinhluong_btn.setForeground(new java.awt.Color(255, 255, 255));
        cleartinhluong_btn.setText("Clear");
        cleartinhluong_btn.setBorderPainted(false);
        cleartinhluong_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cleartinhluong_btn.setFocusPainted(false);
        cleartinhluong_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleartinhluong_btnActionPerformed(evt);
            }
        });
        PanelTinhLuong.add(cleartinhluong_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 90, 31));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Họ tên:");
        PanelTinhLuong.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 50, 24));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Người nhập:");
        PanelTinhLuong.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 24));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Hệ số lương:");
        PanelTinhLuong.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 90, 30));

        hotennv_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hotennv_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelTinhLuong.add(hotennv_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 140, 24));

        nguoinhap_tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PanelTinhLuong.add(nguoinhap_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 140, 24));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Lương cơ bản:");
        PanelTinhLuong.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, 20));

        hesoluong_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hesoluong_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelTinhLuong.add(hesoluong_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 140, 30));

        luongcb_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        luongcb_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelTinhLuong.add(luongcb_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 140, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Tổng($):");
        PanelTinhLuong.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, 30));

        printluong_btn.setBackground(new java.awt.Color(0, 255, 255));
        printluong_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        printluong_btn.setForeground(new java.awt.Color(255, 255, 255));
        printluong_btn.setText("Print");
        printluong_btn.setBorderPainted(false);
        printluong_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printluong_btn.setFocusPainted(false);
        printluong_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printluong_btnActionPerformed(evt);
            }
        });
        PanelTinhLuong.add(printluong_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 90, 31));

        resettbluong_btn.setBackground(new java.awt.Color(51, 255, 51));
        resettbluong_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resettbluong_btn.setForeground(new java.awt.Color(255, 255, 255));
        resettbluong_btn.setText("Reset");
        resettbluong_btn.setBorderPainted(false);
        resettbluong_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resettbluong_btn.setFocusPainted(false);
        resettbluong_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resettbluong_btnActionPerformed(evt);
            }
        });

        cleartbluong_btn.setBackground(new java.awt.Color(255, 51, 51));
        cleartbluong_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cleartbluong_btn.setForeground(new java.awt.Color(255, 255, 255));
        cleartbluong_btn.setText("Clear");
        cleartbluong_btn.setBorderPainted(false);
        cleartbluong_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cleartbluong_btn.setFocusPainted(false);
        cleartbluong_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleartbluong_btnActionPerformed(evt);
            }
        });

        printtbluong_btn.setBackground(new java.awt.Color(0, 51, 255));
        printtbluong_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        printtbluong_btn.setForeground(new java.awt.Color(255, 255, 255));
        printtbluong_btn.setText("Print");
        printtbluong_btn.setBorderPainted(false);
        printtbluong_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printtbluong_btn.setFocusPainted(false);
        printtbluong_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printtbluong_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainluongPanelLayout = new javax.swing.GroupLayout(mainluongPanel);
        mainluongPanel.setLayout(mainluongPanelLayout);
        mainluongPanelLayout.setHorizontalGroup(
            mainluongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainluongPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(mainluongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainluongPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250)
                        .addComponent(troveluong_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainluongPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(timkiem_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(290, 290, 290)
                        .addComponent(resettbluong_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cleartbluong_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(printtbluong_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainluongPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelTinhLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        mainluongPanelLayout.setVerticalGroup(
            mainluongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainluongPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(mainluongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainluongPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(troveluong_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(mainluongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timkiem_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resettbluong_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cleartbluong_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printtbluong_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainluongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelTinhLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainluongPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainluongPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void troveluong_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_troveluong_btnActionPerformed
        hv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_troveluong_btnActionPerformed

    private void updateluong_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateluong_btnActionPerformed
        String manv = manvluong_tf.getText();
        String luongcb_text = luongnvluong_tf.getText();
        String hesoluong_text = hesoluongnvluong_tf.getText();
        if(manv.isBlank() || !manv.matches("A[0-9]{4}")){
            JOptionPane.showMessageDialog(null, "Mã nhân viên bắt đầu bằng chữ A và có 5 ký tự!","",JOptionPane.INFORMATION_MESSAGE);
        } else if(!luongcb_text.matches("\\d+(\\.\\d+)?")){
            JOptionPane.showMessageDialog(null, "Lương cơ bản phải lớn hơn không và không để trống!","",JOptionPane.INFORMATION_MESSAGE);
        } else if(!hesoluong_text.matches("\\d+(\\.\\d+)?")){
            JOptionPane.showMessageDialog(null, "Hệ số lương phải lớn hơn không và không để trống!","",JOptionPane.INFORMATION_MESSAGE);
        } else {
            int check = JOptionPane.showConfirmDialog(null,"Bạn có muốn cập nhật nhân viên này không?", "Cập nhật nhân viên", JOptionPane.YES_NO_OPTION);
            if(check == 0){
                float luongcb = Float.parseFloat(luongnvluong_tf.getText());
                float hesoluong = Float.parseFloat(hesoluongnvluong_tf.getText());
                NhanVien nv = new NhanVien();
                nv.setMaNV(manv);
                nv.setHeSoLuong(hesoluong);
                nv.setLuongCB(luongcb);
                NhanVienDAO nhanviendao = new NhanVienDAO();
                boolean kt = nhanviendao.checkMaNV(manv);
                if(kt){
                    System.out.println(kt);
                    nhanviendao.updateLuong(nv);
                } else {
                    JOptionPane.showMessageDialog(null, "Mã nhân viên không tồn tại!");
                    System.out.println(kt);
                }
                
            } 
        }
    }//GEN-LAST:event_updateluong_btnActionPerformed

    private void clearluong_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearluong_btnActionPerformed

        manvluong_tf.setText("'A0000' Enter");
        manvluong_tf.setForeground(new Color(153,153,153));
        hotennvluong_tf.setText("");
        luongnvluong_tf.setText("");
        hesoluongnvluong_tf.setText("");
    }//GEN-LAST:event_clearluong_btnActionPerformed

    private void timkiem_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_timkiem_tfKeyReleased
        
        DefaultTableModel tableModel = (DefaultTableModel) luongtable.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(tableModel);
        luongtable.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(timkiem_tf.getText()));
    }//GEN-LAST:event_timkiem_tfKeyReleased

    private void resettbluong_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resettbluong_btnActionPerformed
        NhanVienDAO nhanviendao = new NhanVienDAO();
        DefaultTableModel tableModel = (DefaultTableModel) luongtable.getModel();
        ArrayList<NhanVien> list = nhanviendao.selectAllNV();
        int i = 1;
        tableModel.setRowCount(0);
        for(NhanVien n: list){
            tableModel.addRow(new Object[]{
                i++,
                n.getMaNV(),
                n.getHoTen(),
                n.getGioiTinh(),
                n.getChucVu().getTenCV(),
                n.getBoPhan().getTenBP(),
                n.getLuongCB(),
                n.getHeSoLuong(),
            });
        }
    }//GEN-LAST:event_resettbluong_btnActionPerformed

    private void printtbluong_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printtbluong_btnActionPerformed
        MessageFormat header = new MessageFormat("DANH SÁCH LƯƠNG NHÂN VIÊN!");
        MessageFormat footer = new MessageFormat("****************************");
        try {
            luongtable.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_printtbluong_btnActionPerformed

    private void manvluong_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manvluong_tfFocusGained
        if(manvluong_tf.getText().equals("'A0000' Enter")){
            manvluong_tf.setText("");
            manvluong_tf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_manvluong_tfFocusGained

    private void manvluong_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manvluong_tfFocusLost
        if(manvluong_tf.getText().equals("")){
            manvluong_tf.setText("'A0000' Enter");
            manvluong_tf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_manvluong_tfFocusLost

    private void cleartbluong_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleartbluong_btnActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) luongtable.getModel();
        tableModel.setRowCount(0);
    }//GEN-LAST:event_cleartbluong_btnActionPerformed

    private void manvcalluong_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manvcalluong_tfFocusGained
        if(manvcalluong_tf.getText().equals("'A0000' Enter")){
            manvcalluong_tf.setText("");
            manvcalluong_tf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_manvcalluong_tfFocusGained

    private void manvcalluong_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manvcalluong_tfFocusLost
        if(manvcalluong_tf.getText().equals("")){
            manvcalluong_tf.setText("'A0000' Enter");
            manvcalluong_tf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_manvcalluong_tfFocusLost

    private void cleartinhluong_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleartinhluong_btnActionPerformed
        manvcalluong_tf.setText("'A0000' Enter");
        manvcalluong_tf.setForeground(new Color(153,153,153));
        nguoinhap_tf.setText("");
        ngaynhan_jcal.setCalendar(null);
        thuongthem_tf.setText("");
        tongtien_lb.setText("");
        hotennv_lb.setText("");
        luongcb_lb.setText("");
        hesoluong_lb.setText("");
    }//GEN-LAST:event_cleartinhluong_btnActionPerformed

    private void manvluong_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manvluong_tfKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String manv = manvluong_tf.getText();            
            NhanVienDAO nhanviendao = new NhanVienDAO();
            NhanVien nhanvien = new NhanVien();
            nhanvien = nhanviendao.selectBymaNV(manv);
            if(nhanvien==null){
                JOptionPane.showMessageDialog(null, "Mã nhân viên không tồn tại!");
                return;
            }
            hotennvluong_tf.setText(nhanvien.getHoTen());
            String luongcb = String.valueOf(nhanvien.getLuongCB());
            luongnvluong_tf.setText(luongcb);
            String hesoluong = String.valueOf(nhanvien.getHeSoLuong());
            hesoluongnvluong_tf.setText(hesoluong);
        }
    }//GEN-LAST:event_manvluong_tfKeyPressed

    private void manvcalluong_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manvcalluong_tfKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String manv = manvcalluong_tf.getText();            
            NhanVienDAO nhanviendao = new NhanVienDAO();
            NhanVien nhanvien = new NhanVien();
            nhanvien = nhanviendao.selectBymaNV(manv);
            if(nhanvien==null){
                JOptionPane.showMessageDialog(null, "Mã nhân viên không tồn tại!");
                return;
            }
            hotennv_lb.setText(nhanvien.getHoTen());
            String luongcb = String.valueOf(nhanvien.getLuongCB());
            luongcb_lb.setText(luongcb);
            String hesoluong = String.valueOf(nhanvien.getHeSoLuong());
            hesoluong_lb.setText(hesoluong);
        }
    }//GEN-LAST:event_manvcalluong_tfKeyPressed

    private void calculateluong_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateluong_btnActionPerformed
        String nguoiNhap = nguoinhap_tf.getText();
        java.util.Date ngayNhan = (java.util.Date) ngaynhan_jcal.getDate();
        String thuongThem_text = thuongthem_tf.getText();
        String maNV = manvcalluong_tf.getText();
        String hoTen = hotennv_lb.getText();
        String luongCB = luongcb_lb.getText();
        String heSL = hesoluong_lb.getText();
        
        if(maNV.isBlank() || !maNV.matches("A[0-9]{4}")){
            JOptionPane.showMessageDialog(null, "Mã nhân viên bắt đầu bằng chữ A, không để trống và có 5 ký tự!");
        } else if(hoTen.isBlank()){
            JOptionPane.showMessageDialog(null, "Họ tên trống! vui lòng nhập mã nhân viên!");
        } else if(luongCB.isBlank()){
            JOptionPane.showMessageDialog(null, "Lương cơ bản trống! vui lòng nhập mã nhân viên!");
        } else if(heSL.isBlank()){
            JOptionPane.showMessageDialog(null, "Hệ số lương trống! vui lòng nhập mã nhân ");
        } else if(nguoiNhap.isBlank() || !nguoiNhap.matches("[a-zA-Z\\s]+")){
            JOptionPane.showMessageDialog(null, "Người nhập không được để trống và là chuỗi!");
        } else if(ngayNhan == null){
            JOptionPane.showMessageDialog(null, "Ngày nhận không được để trống!");
        } else if(!thuongThem_text.matches("\\d+(\\.\\d+)?")){
            JOptionPane.showMessageDialog(null, "Thưởng thêm là số dương và không chứa ký tự!");
        } else {
            float luongcb = Float.parseFloat(luongcb_lb.getText());
            float hesoluong = Float.parseFloat(hesoluong_lb.getText());
            float thuongThem = Float.parseFloat(thuongthem_tf.getText());
            float tong = luongcb*hesoluong + thuongThem;
            String tongTien = String.valueOf(tong);
            tongtien_lb.setText(tongTien);
        }
    }//GEN-LAST:event_calculateluong_btnActionPerformed

    private void saveluong_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveluong_btnActionPerformed
        String nguoiNhap = nguoinhap_tf.getText();
        java.util.Date ngayNhan = (java.util.Date) ngaynhan_jcal.getDate();
        String thuongThem_text = thuongthem_tf.getText();
        String maNV = manvcalluong_tf.getText();
        String hoTen = hotennv_lb.getText();
        String luongCB = luongcb_lb.getText();
        String heSL = hesoluong_lb.getText();
        String tongText = tongtien_lb.getText();
        
        if(maNV.isBlank() || !maNV.matches("A[0-9]{4}")){
            JOptionPane.showMessageDialog(null, "Mã nhân viên bắt đầu bằng chữ A, không để trống và có 5 ký tự!");
        } else if(hoTen.isBlank()){
            JOptionPane.showMessageDialog(null, "Họ tên trống! vui lòng nhập mã nhân viên!");
        } else if(luongCB.isBlank()){
            JOptionPane.showMessageDialog(null, "Lương cơ bản trống! vui lòng nhập mã nhân viên!");
        } else if(heSL.isBlank()){
            JOptionPane.showMessageDialog(null, "Hệ số lương trống! vui lòng nhập mã nhân ");
        } else if(nguoiNhap.isBlank() || !nguoiNhap.matches("[a-zA-Z\\s]+")){
            JOptionPane.showMessageDialog(null, "Người nhập không được để trống và là chuỗi!");
        } else if(ngayNhan == null){
            JOptionPane.showMessageDialog(null, "Ngày nhận không được để trống!");
        } else if(!thuongThem_text.matches("\\d+(\\.\\d+)?")){
            JOptionPane.showMessageDialog(null, "Thưởng thêm là số dương và không chứa ký tự!");
        } else if(tongText.isBlank()){
            JOptionPane.showMessageDialog(null, "Vui lòng tính tổng lương!");
        } else {
            int check = JOptionPane.showConfirmDialog(null, "Bạn có muốn lưu!", "Lưu biên nhận", JOptionPane.YES_NO_OPTION);
            if(check == 0){
                float luongcb = Float.parseFloat(luongcb_lb.getText());
                float hesoluong = Float.parseFloat(hesoluong_lb.getText());
                float thuongThem = Float.parseFloat(thuongthem_tf.getText());
                float tongTien = Float.parseFloat(tongText);
                NhanVien nhanvien = new NhanVien();
                nhanvien.setMaNV(maNV);
                nhanvien.setHoTen(hoTen);
                nhanvien.setHeSoLuong(hesoluong);
                nhanvien.setHeSoLuong(hesoluong);
                BienNhanDAO biennhandao = new BienNhanDAO();
                int maBN = biennhandao.countAllBienNhan()+1;
                BienNhan biennhan = new BienNhan(maBN, nhanvien, thuongThem, tongTien, ngayNhan, nguoiNhap);
                biennhandao.insert(biennhan);
            }
            
        }
    }//GEN-LAST:event_saveluong_btnActionPerformed

    public static String temp_nguoiNhap,
            temp_ngayNhan,
            temp_thuongThem,
            temp_maNV,
            temp_hoTen,
            temp_tong,
            temp_maBN;
     
    private void printluong_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printluong_btnActionPerformed
        BienNhanDAO biennhandao = new BienNhanDAO();
        temp_nguoiNhap = nguoinhap_tf.getText();
        Date ngayNhan = ngaynhan_jcal.getDate();
        SimpleDateFormat fm = new SimpleDateFormat("dd/MM/yyyy");   
        temp_ngayNhan = fm.format(ngayNhan);
        temp_thuongThem = thuongthem_tf.getText();
        temp_maNV = manvcalluong_tf.getText();
        temp_hoTen = hotennv_lb.getText();
        temp_tong = tongtien_lb.getText();
        temp_maBN = String.valueOf(biennhandao.countAllBienNhan());
        inBienNhanView inbiennhanview = new inBienNhanView();
        inbiennhanview.setVisible(true);
        dispose();
    }//GEN-LAST:event_printluong_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(luongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(luongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(luongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(luongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new luongView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTinhLuong;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calculateluong_btn;
    private javax.swing.JButton clearluong_btn;
    private javax.swing.JButton cleartbluong_btn;
    private javax.swing.JButton cleartinhluong_btn;
    private javax.swing.JLabel hesoluong_lb;
    private javax.swing.JTextField hesoluongnvluong_tf;
    private javax.swing.JLabel hotennv_lb;
    private javax.swing.JLabel hotennvluong_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel luongcb_lb;
    private javax.swing.JTextField luongnvluong_tf;
    private javax.swing.JTable luongtable;
    private javax.swing.JPanel mainluongPanel;
    private javax.swing.JTextField manvcalluong_tf;
    private javax.swing.JTextField manvluong_tf;
    private com.toedter.calendar.JDateChooser ngaynhan_jcal;
    private javax.swing.JTextField nguoinhap_tf;
    private javax.swing.JButton printluong_btn;
    private javax.swing.JButton printtbluong_btn;
    private javax.swing.JButton resettbluong_btn;
    private javax.swing.JButton saveluong_btn;
    private javax.swing.JTextField thuongthem_tf;
    private javax.swing.JTextField timkiem_tf;
    private javax.swing.JLabel tongtien_lb;
    private javax.swing.JButton troveluong_btn;
    private javax.swing.JButton updateluong_btn;
    // End of variables declaration//GEN-END:variables
}
